<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NAudio.PipeWirePlay.Sample</AssemblyName>
    <RootNamespace>NAudio.PipeWirePlay.Sample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Core" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NAudio.PipeWirePlay\NAudio.PipeWirePlay.csproj" />
  </ItemGroup>
</Project>
